# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_matern_prec_matrix_2d_cpp <- function(a, dim) {
    .Call(`_cholesky_make_matern_prec_matrix_2d_cpp`, a, dim)
}

cholesky_bandsparse_cpp <- function(A) {
    .Call(`_cholesky_cholesky_bandsparse_cpp`, A)
}

compute_marginal_variances_cpp <- function(L) {
    .Call(`_cholesky_compute_marginal_variances_cpp`, L)
}

make_standardized_matern_cpp <- function(a, dim) {
    .Call(`_cholesky_make_standardized_matern_cpp`, a, dim)
}

make_matern_prec_matrix_2d_cpp_eigen <- function(a, dim) {
    .Call(`_cholesky_make_matern_prec_matrix_2d_cpp_eigen`, a, dim)
}

cholesky_bandsparse_cpp_eigen <- function(A) {
    .Call(`_cholesky_cholesky_bandsparse_cpp_eigen`, A)
}

compute_marginal_variances_cpp_eigen <- function(L) {
    .Call(`_cholesky_compute_marginal_variances_cpp_eigen`, L)
}

make_standardized_matern_cpp_eigen <- function(a, dim) {
    .Call(`_cholesky_make_standardized_matern_cpp_eigen`, a, dim)
}

make_AR_prec_matrix_sparse <- function(dim, rho) {
    .Call(`_cholesky_make_AR_prec_matrix_sparse`, dim, rho)
}

make_matern_prec_matrix_sparse <- function(dim, rho) {
    .Call(`_cholesky_make_matern_prec_matrix_sparse`, dim, rho)
}

compute_marginal_variances_sparse <- function(Q) {
    .Call(`_cholesky_compute_marginal_variances_sparse`, Q)
}

make_standardized_matern_sparse <- function(dim, rho) {
    .Call(`_cholesky_make_standardized_matern_sparse`, dim, rho)
}

